#!/bin/sh /etc/rc.common

START=99
start() {
        echo "Starting plantduino-command-listener"
        python /root/command-listener.py &
}

stop() {
        pid=$(ps | grep '[p]ython /root/command-listener.py' | awk '{ print $1 }')
        echo "Stopping plantduino-command-listener"
        kill $pid
        echo "Stopped plantduino-command-listener"
}
