#!/bin/sh /etc/rc.common

START=30
start() {
        echo "Starting plantduino-notifications"
	. /etc/profile
        python /root/notifications.py &
}

stop() {
        pid=$(ps | grep '[p]ython /root/notifications.py' | awk '{ print $1 }')
        echo "Stopping plantduino-notifications"
        kill $pid
        echo "Stopped plantduino-notifications"
}
